# wrangler.toml para Cloudflare Pages
name = "baltc-liga"
compatibility_date = "2025-01-20"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "baltc_liga_dev"
database_id = "11111111-1111-1111-1111-111111111111"