# wrangler.toml para Cloudflare Pages
name = "baltc-liga"
compatibility_date = "2025-01-20"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "baltc-db"
database_id = "ca7ea78d-e491-433c-9f79-fc245235a35a"