# wrangler.toml para Cloudflare Pages
name = "baltc-liga"
compatibility_date = "2025-01-20"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "baltc_liga_prod"
database_id = "79d8f80c-2a5e-4843-898a-4640a4296201"