# wrangler.toml para Cloudflare Pages - PRODUCCIÓN
name = "baltc-liga"
compatibility_date = "2025-01-20"
pages_build_output_dir = "./public"

# Base de datos para producción
[[d1_databases]]
binding = "DB"
database_name = "baltc-db"
database_id = "ca7ea78d-e491-433c-9f79-fc245235a35a"

# Workers AI - Modelo Llama 3.1 8B (gratuito)
[ai]
binding = "AI"

# KV para memoria de conversaciones
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "d6bdd7cff5564a88b218301bdc4af27f"
